language: python
dist: xenial
python:
  - "3.5"
  - "3.6"
  - "3.7"
install:
  - pip install -e .[dev]
script:
  - pycodestyle -v --statistics --exclude=setup.py
  - nosetests --with-coverage --cover-erase --cover-package=lib.susepubliccloudinfoclient --cover-xml
deploy:
  provider: pypi
  user: "__token__"
  password: $PYPI_PASS
  on:
    tags: true
  skip_existing: true
