language: python
dist: xenial
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
install:
  - pip install -e
script:
  - make pep8
  - make test
deploy:
  provider: pypi
  user: "suse-pub-cloud-dev"
  password: $PYPI_PASS
  on:
    tags: true
  skip_existing: true
